---
- id: go-fmt
  name: go fmt
  entry: x-hook-go-fmt.sh
  files: "\\.go$"
  language: script
  description: "Execs `gofmt`, requires golang"
- id: go-vet
  name: go vet
  entry: x-hook-go-vet.sh
  files: ""
  pass_filenames: false
  language: script
  description: "Execs `go vet`, requires golang"
- id: golangci-lint
  name: golangci-lint
  entry: x-hook-golangci-lint.sh
  types:
    - go
  language: script
  pass_filenames: false
  description: "Execs `golangci-lint`, golangci-lint"
- id: golangci-megalint
  name: golangci-megalint
  entry: x-hook-golangci-megalint.sh
  types:
    - go
  language: script
  pass_filenames: false
  description: "Execs `golangci-lint` with all flags"
- id: go-unit-tests
  name: go-unit-tests
  entry: x-hook-go-unit-tests.sh
  files: "\\.go$"
  language: script
  description: "Execs `go test`"
- id: go-build
  name: go-build
  entry: x-hook-go-build.sh
  files: "\\.go$"
  language: script
  description: "Execs `go build`, requires golang"
- id: commitlint
  name: commitlint
  entry: x-hook-commitlint.sh
  files: ""
  language: script
  description: "Execs `commitlint` -f HEAD, requires commitlint"
- id: yamllint
  name: yamllint
  entry: x-hook-yamllint.sh
  files: "\\.yaml$"
  language: script
  description: "Execs `yamllint` -s @, requires yamllint"
- id: markdownlint
  name: markdownlint
  entry: x-hook-markdownlint.sh
  files: "\\.md$"
  language: script
  description: "Execs `markdownlint` --fix @, requires markdownlintcli"
- id: black
  name: black
  entry: x-hook-black.sh
  files: "\\.py$"
  language: script
  description: "Execs `black` --line-length=120 @, requires black"
- id: isort
  name: isort
  entry: x-hook-isort.sh
  files: "\\.py$"
  language: script
  description: "Execs `isort` --atomic --apply --recursive  @, requires isort"
- id: flake8
  name: flake8
  entry: x-hook-flake8.sh
  files: "\\.py$"
  language: script
  description: "Execs `flake8` --max-line-length=120 @, requires flake8"
- id: checkyml
  name: checkyml
  entry: x-hook-checkyml.sh
  files: "\\.yml$"
  language: script
  description: "Checks for files with the .yml extension"
- id: gitcheck
  name: gitcheck
  entry: x-hook-gitcheck.sh
  files: ""
  language: script
  description: "Checks for conflict markers, core.whitespace errors, etc.."
